### ISSUE TITLE
UTF-8 and HTML entity encoding

### ISSUE THREAD

**Issue by ryanoverbey** [CodeAtCode/Glossary#45]
When attempting to use the Glossary plugin, I ran into a problem of UTF-8 strings not matching. This is because search strings are stored in the db as raw UTF-8, but UTF-8 in Wordpress pages and posts is stored as html entity-encoded text.

So searching for the term Báb, we find that the stored term is `B\xc3\xa1b`, whereas the post text stores the same term as `B&aacute;b`

I solved this by editing the function search_string as follows in Glossary_Tooltip_Engine.php

`  public function search_string( $title ) {
    return '/(?<!\w)((?i)' . preg_quote(mb_convert_encoding($title, 'HTML-ENTITIES')) . '(?-i))(?=[ \.\,\:\;\*\"\)\!\?\/\%\$\£\|\^\<\>])(?![^<]*(<\/a>|<\/span>|" \/>|>))/';
  }`

**Comment by Mte90** [comment]
amazing, what you say @EugenioPetulla about it?

**Comment by EugenioPetulla** [comment]
I'm testing out @ryanoverbey 's solution just now. I'll let you know if everything is ok.

Thank you for the effort and the usefull feedback!

**Comment by EugenioPetulla** [comment]
@ryanoverbey are you sure this is a general issue? Because I'm not comparing the DB string but just the rendered output that cames from the WP engine AFTER it retrieves the data from database, and in this moment the data is already transformed using the encoding you choosed in the database config of your wp-config.php, like if you are printing out the title using the function provided by WordPress itself.

Take a look at this page and search for my name (Eugenio Petullà), actually it works well without your code and it doesn't if I apply it: https://codeat.co/glossary/hello-world/

What heppens if you try to print out a simple `get_the_title();` of a post that has a special char in it? Our plugin works the same, doesn't use the raw DB data at all. :)

**Comment by ryanoverbey** [comment]
This is curious.

I inserted an error_log($title) in the search_string function, and for some reason this is how PHP is seeing titles and related terms:

`[Wed Jun 22 09:38:28 2016] [error] B\xc3\xa1b
[Wed Jun 22 09:38:28 2016] [error] B\xc3\xa1b\xe2\x80\x99s
[Wed Jun 22 09:38:28 2016] [error] Bab
[Wed Jun 22 09:38:28 2016] [error] Bab\xe2\x80\x99s`

This is for a glossary with title Báb, and related comma separated terms Báb’s,Bab,Bab’s

When I error_log the post content, Wordpress has auto-sanitized the post content, so that all occurrences of the term read B&aacute;b, and the preg_ functions weren’t matching them. My little patch is the only way to get the term to properly link on my site.

You may be right that this could be an issue specific to my installation. I’ll keep investigating, and will let you know if I find any general issues that need attention. Thanks for taking the time to look into it on your end!

**Comment by Mte90** [comment]
Maybe we can add a filter so you can change the code as you prefer for the search part.

**Comment by EugenioPetulla** [comment]
Defitnely YES @Mte90 , we have to do it! Developer first! :D

@ryanoverbey I suggest to you to switch theme for a while (use a standar one like twenty-something) and see if is a theme related stuff.

Sometimes themes' authors change the natural "WordPress Way" in order to accomplish a better design.

Another try: use the encoded char instead of the rendered one in the title and see what happens! :)

**Comment by Mte90** [comment]
I added a filter to customize the regex so in the meantime we can investigate further without create problems to you.
