### ISSUE TITLE
Glossary doesn't allow admin enter to settings -version unsupported yet!-

### ISSUE THREAD

**Issue by aldobelus0** [CodeAtCode/Glossary#57]
When I, the admin of the Wordpress blog, try to enter to the settings of Glossary appears a message saying: "sorry, you're not allowed to access this page" (maybe in english isn't the same, I'm translating from spanish). But, I repeat, I'm the only one who can access to the blog administration. 

I warn, I have the version 4.6.1., which isn't supported by your plugin. I'm only providing you feedback.

**Comment by EugenioPetulla** [comment]
Only the administrator (admin standard wordpress role) is able to configure the glossary settings. I'm not able to reproduce the bug and I'm testing it with 4.6.1 version. I need more information in order to debug this, sorry for the questions. 

Are you sure that your role is right and that you don't have limited privileges? Are you the developer of your website? Are you able to install and manage plugins with your user?

**Comment by aldobelus0** [comment]
![aldobelus-admin](https://cloud.githubusercontent.com/assets/15985449/19839608/4509f0d6-9ee5-11e6-9d0e-c9909a326c0f.png)

**Comment by Mte90** [comment]
To add the admin page settings use the standard way, checking for the manage_options capabilities.
As I can understand you have the link but when you try to open the page you get the error.
The code is very standard so I am not sure what to do next, maybe your website have a specific settings?

**Comment by Mte90** [comment]
I close that for no updates about the reporter, in case of new updates we will open again.

**Comment by aldobelus0** [comment]
It's not happening now, so forget it. I don't know why have changed its behaviour, but it did. I'm working on Glossary normally now.
